/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ubt.healthcare.ui.admin;

import java.awt.event.MouseAdapter;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author F
 */
public class JFAdminScreen extends javax.swing.JFrame {

    private JIFDoctor jifDoctor;

    /**
     * Creates new form JFAdminScreen
     */
    public JFAdminScreen() {
        initComponents();
    }

    public JFAdminScreen(JIFDoctor jifDoctor) {
        this.jifDoctor = jifDoctor;

        //frameStlye();
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPaneHandler = new javax.swing.JDesktopPane();
        jlProfile = new javax.swing.JLabel();
        jlDoctor = new javax.swing.JLabel();
        jlReceptionist = new javax.swing.JLabel();
        jlPharmacist = new javax.swing.JLabel();
        jlPharmacyManager = new javax.swing.JLabel();
        jlNurse = new javax.swing.JLabel();
        jlAdminClinic = new javax.swing.JLabel();
        jlLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpPaneHandlerLayout = new javax.swing.GroupLayout(jdpPaneHandler);
        jdpPaneHandler.setLayout(jdpPaneHandlerLayout);
        jdpPaneHandlerLayout.setHorizontalGroup(
            jdpPaneHandlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jdpPaneHandlerLayout.setVerticalGroup(
            jdpPaneHandlerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        jlProfile.setText("Profile");

        jlDoctor.setText("Doctor");

        jlReceptionist.setText("Receptionist");

        jlPharmacist.setText("Pharmacist");

        jlPharmacyManager.setText("Pharmacy Manager");

        jlNurse.setText("Nurse");

        jlAdminClinic.setText("Admin");

        jlLogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPaneHandler)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jlDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(jlReceptionist, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(jlPharmacist, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(jlPharmacyManager, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addComponent(jlNurse, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(jlAdminClinic, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addComponent(jlLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlReceptionist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlPharmacist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlPharmacyManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlNurse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlAdminClinic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jdpPaneHandler))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdpPaneHandler;
    private javax.swing.JLabel jlAdminClinic;
    private javax.swing.JLabel jlDoctor;
    private javax.swing.JLabel jlLogout;
    private javax.swing.JLabel jlNurse;
    private javax.swing.JLabel jlPharmacist;
    private javax.swing.JLabel jlPharmacyManager;
    private javax.swing.JLabel jlProfile;
    private javax.swing.JLabel jlReceptionist;
    // End of variables declaration//GEN-END:variables

    public void addLogOutMouseAdapter(MouseAdapter e) {
        jlLogout.addMouseListener(e);
    }

    public void addDoctorScreenMouseAdapter(MouseAdapter e) {
        jlDoctor.addMouseListener(e);
    }

    public void addAddReceptionistMouseAdapter(MouseAdapter e) {
        jlReceptionist.addMouseListener(e);
    }

    public void addViewProfileMouseAdapter(MouseAdapter e) {
        jlProfile.addMouseListener(e);
    }

    public void addNurseScreenMouseAdapter(MouseAdapter e) {
        jlNurse.addMouseListener(e);
    }

    public void addAdminClinicScreenMouseAdapter(MouseAdapter e) {
        jlAdminClinic.addMouseListener(e);
    }

    public void addPharmacistScreenMouseAdapter(MouseAdapter e) {
        jlPharmacist.addMouseListener(e);
    }

    public void addPharmacyManagerScreenMouseAdapter(MouseAdapter e) {
        jlPharmacyManager.addMouseListener(e);
    }

    public void showDoctorScreen() {

        jdpPaneHandler.remove(jifDoctor);
        jdpPaneHandler.add(jifDoctor);
        jifDoctor.show();
        /*jspPane.setViewportView(jpAddDoctor);
        jspPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);*/

    }

    public void showAddDoctorInternalFrame() {
        // remove internalframe from desktop pane
        jdpPaneHandler.remove(jifDoctor.getJifAddDoctor());

        jdpPaneHandler.add(jifDoctor.getJifAddDoctor());

        jifDoctor.getJifAddDoctor().show();

        // load city combobox
        //jifDoctor.getJifAddDoctor().loadCityComboBox();
        // set the DoctorService
        //jifDoctor.getJifViewDoctor().setDoctorService(jifDoctor.getDoctorService());
        //set Doctor
        //jifDoctor.getJifViewDoctor().setDoctor(jifDoctor.getDoctor());
        // hide the View Doctor Internal Pane
        jifDoctor.hide();
    }

    public void showSearchDoctorInternalFrame() {
        // remove internalframe from desktop pane
        jdpPaneHandler.remove(jifDoctor.getJifViewDoctor());

        jdpPaneHandler.add(jifDoctor.getJifViewDoctor());

        jifDoctor.getJifViewDoctor().show();

        // load city combobox
        jifDoctor.getJifViewDoctor().loadCityComboBox();

        // set the DoctorService
        jifDoctor.getJifViewDoctor().setDoctorService(jifDoctor.getDoctorService());
        //set Doctor
        jifDoctor.getJifViewDoctor().setDoctor(jifDoctor.getDoctor());
        // hide the View Doctor Internal Pane
        jifDoctor.hide();
    }

    public void showAddCityInternalFrame() {
        jdpPaneHandler.remove(jifDoctor.getJifAddCity());
        jdpPaneHandler.add(jifDoctor.getJifAddCity());
        jifDoctor.getJifAddCity().show();
        try {
            jifDoctor.getJifAddCity().setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFAdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void showAddCountryInternalFrame() {
        jdpPaneHandler.remove(jifDoctor.getJifAddCountry());
        jdpPaneHandler.add(jifDoctor.getJifAddCountry());
        jifDoctor.getJifAddCountry().show();
        try {
            jifDoctor.getJifAddCountry().setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(JFAdminScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void showEditDoctorInternalFrame() {

        if (jifDoctor.getDoctor() == null) {
            JOptionPane.showMessageDialog(rootPane, "Choose doctor you want to edit");
        } else {
            // remove internalframe from desktop pane
            jdpPaneHandler.remove(jifDoctor.getJifEditDoctor());

            jdpPaneHandler.add(jifDoctor.getJifEditDoctor());

            jifDoctor.getJifEditDoctor().show();

            jifDoctor.getJifEditDoctor().setDoctor(jifDoctor.getDoctor());
            jifDoctor.getJifEditDoctor().updateDoctorFields(jifDoctor.getDoctor());

            // hide the View Doctor Internal Pane
            jifDoctor.hide();
        }
    }

    public JIFDoctor getJifDoctor() {
        return jifDoctor;
    }

    static {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());

                    /*jdpPaneHandler.setUI(new DesktopPaneUI() {
                        @Override
                        public void installUI(JComponent ui) {
                            try {
                                UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel.");

                            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
                            }
                        }
                    });*/
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            System.out.println("UI Manager not found");
        }
    }
}
